//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../magicstick-ui/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "battery-report": $$createType0,
        "device-disconnected": $$createType1,
        "rpc-event": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = main$0.BatteryReportEvent.createFrom;
const $$createType1 = main$0.DeviceDisconnectedEvent.createFrom;
const $$createType2 = main$0.RpcEvent.createFrom;

configure();
