//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

func main() {
	// Get the directory where this file is located
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Dir(filename)

	// Try to read version.txt file (MAJOR.MINOR format) - relative to this file's directory
	versionFile := filepath.Join(dir, "..", "version.txt")
	versionData, err := os.ReadFile(versionFile)
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not read version.txt: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	baseVersion := strings.TrimSpace(string(versionData))
	if baseVersion == "" {
		fmt.Println("//go:generate: Warning: version.txt is empty")
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	// Try to get git commit count for PATCH version
	var commitCount string
	var commitHash string

	cmd := exec.Command("git", "rev-list", "--count", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not get git commit count: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	commitCount = strings.TrimSpace(string(output))
	patch, err := strconv.Atoi(commitCount)
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not parse commit count: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	// Try to get git commit hash
	cmd = exec.Command("git", "rev-parse", "--short", "HEAD")
	output, err = cmd.Output()
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not get git commit hash: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	commitHash = strings.TrimSpace(string(output))

	// Generate version string
	version := fmt.Sprintf("%s.%d-sha.%s", baseVersion, patch, commitHash)

	// Generate the version.go file
	versionGoContent := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package main

var (
	Version         = "%s"
	GitCommit       = "%s"
	GitCommitCount  = "%s"
)
`, version, commitHash, commitCount)

	versionGoPath := filepath.Join(dir, "version.go")
	err = os.WriteFile(versionGoPath, []byte(versionGoContent), 0644)
	if err != nil {
		fmt.Printf("//go:generate: Error writing version.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated version.go with version: %s\n", version)

	// Update wails.json with the new version
	wailsJsonPath := filepath.Join(dir, "wails.json")
	err = updateWailsJsonVersion(wailsJsonPath, version)
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not update wails.json: %v\n", err)
	} else {
		fmt.Printf("Updated wails.json with version: %s\n", version)
	}
}

// WailsConfig represents the structure of wails.json
type WailsConfig struct {
	Schema               string            `json:"$schema"`
	Name                 string            `json:"name"`
	OutputFilename       string            `json:"outputfilename"`
	FrontendInstall      string            `json:"frontend:install"`
	FrontendBuild        string            `json:"frontend:build"`
	FrontendDevWatcher   string            `json:"frontend:dev:watcher"`
	FrontendDevServerURL string            `json:"frontend:dev:serverUrl"`
	PreBuildHooks        map[string]string `json:"preBuildHooks"`
	Info                 struct {
		ProductName    string `json:"productName"`
		ProductVersion string `json:"productVersion"`
		Copyright      string `json:"copyright"`
	} `json:"info"`
}

func updateWailsJsonVersion(wailsJsonPath, version string) error {
	// Read the existing wails.json file
	data, err := os.ReadFile(wailsJsonPath)
	if err != nil {
		return fmt.Errorf("could not read wails.json: %v", err)
	}

	// Parse the JSON
	var config WailsConfig
	err = json.Unmarshal(data, &config)
	if err != nil {
		return fmt.Errorf("could not parse wails.json: %v", err)
	}

	// Update the product version
	config.Info.ProductVersion = version

	// Write back to file with proper formatting
	updatedData, err := json.MarshalIndent(config, "", "    ")
	if err != nil {
		return fmt.Errorf("could not marshal updated config: %v", err)
	}

	err = os.WriteFile(wailsJsonPath, updatedData, 0644)
	if err != nil {
		return fmt.Errorf("could not write updated wails.json: %v", err)
	}

	return nil
}
