//go:build ignore

package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

func main() {
	// Get the directory where this file is located
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Dir(filename)

	// Try to read version.txt file (MAJOR.MINOR format) - relative to this file's directory
	versionFile := filepath.Join(dir, "..", "version.txt")
	versionData, err := os.ReadFile(versionFile)
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not read version.txt: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	baseVersion := strings.TrimSpace(string(versionData))
	if baseVersion == "" {
		fmt.Println("//go:generate: Warning: version.txt is empty")
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	// Try to get git commit count for PATCH version
	var commitCount string
	var commitHash string

	cmd := exec.Command("git", "rev-list", "--count", "HEAD")
	output, err := cmd.Output()
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not get git commit count: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	commitCount = strings.TrimSpace(string(output))
	patch, err := strconv.Atoi(commitCount)
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not parse commit count: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	// Try to get git commit hash
	cmd = exec.Command("git", "rev-parse", "--short", "HEAD")
	output, err = cmd.Output()
	if err != nil {
		fmt.Printf("//go:generate: Warning: Could not get git commit hash: %v\n", err)
		fmt.Println("//go:generate: Skipping version generation")
		return
	}

	commitHash = strings.TrimSpace(string(output))

	// Generate version string
	version := fmt.Sprintf("%s.%d-sha.%s", baseVersion, patch, commitHash)

	// Generate the version.go file
	versionGoContent := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package main

var (
	Version         = "%s"
	GitCommit       = "%s"
	GitCommitCount  = "%s"
)
`, version, commitHash, commitCount)

	versionGoPath := filepath.Join(dir, "version.go")
	err = os.WriteFile(versionGoPath, []byte(versionGoContent), 0644)
	if err != nil {
		fmt.Printf("//go:generate: Error writing version.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated version.go with version: %s\n", version)
}
