// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlendIconData(arg1) {
  return window['go']['main']['App']['BlendIconData'](arg1);
}

export function GetAutostartStatus() {
  return window['go']['main']['App']['GetAutostartStatus']();
}

export function GetAvailableIcons() {
  return window['go']['main']['App']['GetAvailableIcons']();
}

export function GetSemVer() {
  return window['go']['main']['App']['GetSemVer']();
}

export function IsDarkMode() {
  return window['go']['main']['App']['IsDarkMode']();
}

export function LoadIconData(arg1) {
  return window['go']['main']['App']['LoadIconData'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetBatteryCallback() {
  return window['go']['main']['App']['SetBatteryCallback']();
}

export function SetDisconnectCallback() {
  return window['go']['main']['App']['SetDisconnectCallback']();
}

export function SetGlobalMagicStickDevice() {
  return window['go']['main']['App']['SetGlobalMagicStickDevice']();
}

export function SetRpcEventCallback() {
  return window['go']['main']['App']['SetRpcEventCallback']();
}

export function SetTrayIcon(arg1) {
  return window['go']['main']['App']['SetTrayIcon'](arg1);
}

export function SetTrayTooltip(arg1) {
  return window['go']['main']['App']['SetTrayTooltip'](arg1);
}
