// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BlendIconData(arg1:Array<string>):Promise<Array<number>>;

export function GetAutostartStatus():Promise<boolean>;

export function GetAvailableIcons():Promise<Array<string>>;

export function GetSemVer():Promise<main.SemVerInfo>;

export function IsDarkMode():Promise<boolean>;

export function LoadIconData(arg1:string):Promise<Array<number>>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetBatteryCallback():Promise<void>;

export function SetDisconnectCallback():Promise<void>;

export function SetGlobalMagicStickDevice():Promise<void>;

export function SetRpcEventCallback():Promise<void>;

export function SetTrayIcon(arg1:Array<number>):Promise<void>;

export function SetTrayTooltip(arg1:string):Promise<void>;
