// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function EnumerateDevices():Promise<Array<main.MagicStickInfo>>;

export function GetKeymap(arg1:boolean):Promise<main.GetKeymapReply>;

export function GetSettings():Promise<main.GetSettingsReply>;

export function Open(arg1:string,arg2:boolean):Promise<void>;

export function RequestBatteryReport():Promise<void>;

export function SaveConfig():Promise<void>;

export function SetBatteryCallback(arg1:any):Promise<void>;

export function SetDisconnectCallback(arg1:any):Promise<void>;

export function SetKeymap(arg1:Array<string>):Promise<main.SetKeymapReply>;

export function SetRpcEventCallback(arg1:any):Promise<void>;

export function SetSettings(arg1:main.SetSettingsRequest):Promise<void>;
