// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['MagicStickDevice']['Close']();
}

export function EnumerateDevices() {
  return window['go']['main']['MagicStickDevice']['EnumerateDevices']();
}

export function GetKeymap(arg1) {
  return window['go']['main']['MagicStickDevice']['GetKeymap'](arg1);
}

export function GetSettings() {
  return window['go']['main']['MagicStickDevice']['GetSettings']();
}

export function Open(arg1, arg2) {
  return window['go']['main']['MagicStickDevice']['Open'](arg1, arg2);
}

export function RequestBatteryReport() {
  return window['go']['main']['MagicStickDevice']['RequestBatteryReport']();
}

export function SaveConfig() {
  return window['go']['main']['MagicStickDevice']['SaveConfig']();
}

export function SetBatteryCallback(arg1) {
  return window['go']['main']['MagicStickDevice']['SetBatteryCallback'](arg1);
}

export function SetDisconnectCallback(arg1) {
  return window['go']['main']['MagicStickDevice']['SetDisconnectCallback'](arg1);
}

export function SetKeymap(arg1) {
  return window['go']['main']['MagicStickDevice']['SetKeymap'](arg1);
}

export function SetRpcEventCallback(arg1) {
  return window['go']['main']['MagicStickDevice']['SetRpcEventCallback'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['MagicStickDevice']['SetSettings'](arg1);
}
