// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SystemTray {

    /** Creates a new SystemTray instance. */
    constructor($$source: Partial<SystemTray> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemTray instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemTray {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemTray($$parsedSource as Partial<SystemTray>);
    }
}
