// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['hid']['Device']['Close']();
}

export function EnumerateDevices() {
  return window['go']['hid']['Device']['EnumerateDevices']();
}

export function GetKeymap(arg1) {
  return window['go']['hid']['Device']['GetKeymap'](arg1);
}

export function GetSettings() {
  return window['go']['hid']['Device']['GetSettings']();
}

export function Open(arg1, arg2) {
  return window['go']['hid']['Device']['Open'](arg1, arg2);
}

export function RequestBatteryReport() {
  return window['go']['hid']['Device']['RequestBatteryReport']();
}

export function SaveConfig() {
  return window['go']['hid']['Device']['SaveConfig']();
}

export function SetBatteryCallback(arg1) {
  return window['go']['hid']['Device']['SetBatteryCallback'](arg1);
}

export function SetDisconnectCallback(arg1) {
  return window['go']['hid']['Device']['SetDisconnectCallback'](arg1);
}

export function SetKeymap(arg1) {
  return window['go']['hid']['Device']['SetKeymap'](arg1);
}

export function SetRpcEventCallback(arg1) {
  return window['go']['hid']['Device']['SetRpcEventCallback'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['hid']['Device']['SetSettings'](arg1);
}
