// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hid} from '../models';

export function Close():Promise<void>;

export function EnumerateDevices():Promise<Array<hid.DeviceInfo>>;

export function GetKeymap(arg1:boolean):Promise<hid.GetKeymapReply>;

export function GetSettings():Promise<hid.GetSettingsReply>;

export function Open(arg1:string,arg2:boolean):Promise<void>;

export function RequestBatteryReport():Promise<void>;

export function SaveConfig():Promise<void>;

export function SetBatteryCallback(arg1:any):Promise<void>;

export function SetDisconnectCallback(arg1:any):Promise<void>;

export function SetKeymap(arg1:Array<string>):Promise<hid.SetKeymapReply>;

export function SetRpcEventCallback(arg1:any):Promise<void>;

export function SetSettings(arg1:hid.SetSettingsRequest):Promise<void>;
