// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService handles application-level operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * BlendIconData blends multiple icon data arrays and returns the result
 * Takes icon paths and returns blended icon data as PNG bytes
 */
export function BlendIconData(iconPaths: string[]): $CancellablePromise<string> {
    return $Call.ByID(3411058436, iconPaths).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetAutostartStatus returns whether autostart is currently enabled
 */
export function GetAutostartStatus(): $CancellablePromise<boolean> {
    return $Call.ByID(1609018541);
}

/**
 * GetVersion returns the application version from build/config.yml
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2729898890);
}

/**
 * IsDarkMode returns true if Windows uses dark mode theme, true for any other OS
 */
export function IsDarkMode(): $CancellablePromise<boolean> {
    return $Call.ByID(597829737);
}

/**
 * LoadIconData loads icon data from the embedded filesystem
 * Returns the raw icon data that can be used for blending
 */
export function LoadIconData(iconPath: string): $CancellablePromise<string> {
    return $Call.ByID(332042327, iconPath).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * SetAutostart enables or disables autostart for the application
 */
export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1760948543, enabled);
}

/**
 * SetSystemTray sets the system tray reference
 */
export function SetSystemTray(systemTray: application$0.SystemTray | null): $CancellablePromise<void> {
    return $Call.ByID(4210695231, systemTray);
}

/**
 * UpdateTrayIcon updates the system tray icon with the provided PNG icon data
 */
export function UpdateTrayIcon(iconData: string): $CancellablePromise<void> {
    return $Call.ByID(3249810206, iconData);
}

/**
 * UpdateTrayTooltip updates the system tray tooltip text
 */
export function UpdateTrayTooltip(tooltip: string): $CancellablePromise<void> {
    return $Call.ByID(3440029678, tooltip);
}
