// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService wraps the hid.Device to expose it as a Wails service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hid$0 from "./hid/models.js";

/**
 * Close closes the currently opened device
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3968491633);
}

/**
 * EnumerateDevices scans the system for Magic Stick devices
 */
export function EnumerateDevices(): $CancellablePromise<(hid$0.DeviceInfo | null)[]> {
    return $Call.ByID(3179492634).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetKeymap retrieves device keymap via RPC
 */
export function GetKeymap(defaults: boolean): $CancellablePromise<hid$0.GetKeymapReply | null> {
    return $Call.ByID(2039460914, defaults).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetSettings retrieves current device settings via RPC
 */
export function GetSettings(): $CancellablePromise<hid$0.GetSettingsReply | null> {
    return $Call.ByID(4158545736).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Open opens a device by serial number and sets up event callbacks
 */
export function Open(serial: string, lock: boolean): $CancellablePromise<void> {
    return $Call.ByID(879756119, serial, lock);
}

/**
 * RequestBatteryReport manually sends a request for battery report
 */
export function RequestBatteryReport(): $CancellablePromise<void> {
    return $Call.ByID(2949887263);
}

/**
 * SaveConfig saves current configuration to device via RPC
 */
export function SaveConfig(): $CancellablePromise<void> {
    return $Call.ByID(18440192);
}

/**
 * SetKeymap updates device keymap via RPC
 */
export function SetKeymap(items: string[]): $CancellablePromise<hid$0.SetKeymapReply | null> {
    return $Call.ByID(3071495878, items).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SetSettings updates device settings via RPC
 */
export function SetSettings(req: hid$0.SetSettingsRequest | null): $CancellablePromise<void> {
    return $Call.ByID(2192192004, req);
}

// Private type creation functions
const $$createType0 = hid$0.DeviceInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = hid$0.GetKeymapReply.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = hid$0.GetSettingsReply.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = hid$0.SetKeymapReply.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
