// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Typed event structures for Wails v3
 */
export class BatteryReportEvent {
    /**
     * Battery status (raw value from device)
     */
    "status": number;

    /**
     * Battery level (0-100)
     */
    "level": number;

    /** Creates a new BatteryReportEvent instance. */
    constructor($$source: Partial<BatteryReportEvent> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("level" in $$source)) {
            this["level"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryReportEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): BatteryReportEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatteryReportEvent($$parsedSource as Partial<BatteryReportEvent>);
    }
}

export class DeviceDisconnectedEvent {
    /**
     * Error message describing the disconnection
     */
    "error": string;

    /** Creates a new DeviceDisconnectedEvent instance. */
    constructor($$source: Partial<DeviceDisconnectedEvent> = {}) {
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceDisconnectedEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceDisconnectedEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceDisconnectedEvent($$parsedSource as Partial<DeviceDisconnectedEvent>);
    }
}

export class RpcEvent {
    /**
     * RPC event name (e.g., "connected", "disconnected")
     */
    "name": string;

    /**
     * RPC event payload (JSON string)
     */
    "payload": string;

    /** Creates a new RpcEvent instance. */
    constructor($$source: Partial<RpcEvent> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RpcEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): RpcEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RpcEvent($$parsedSource as Partial<RpcEvent>);
    }
}
