// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MagicStickInfo represents an enumerated candidate device before opening.
 */
export class DeviceInfo {
    "Index": number;
    "VendorID": number;
    "ProductID": number;

    /**
     * Device Model (from Product())
     */
    "Product": string;

    /**
     * Device Serial (from SerialNumber())
     */
    "Serial": string;
    "Manufacturer": string;

    /** Creates a new DeviceInfo instance. */
    constructor($$source: Partial<DeviceInfo> = {}) {
        if (!("Index" in $$source)) {
            this["Index"] = 0;
        }
        if (!("VendorID" in $$source)) {
            this["VendorID"] = 0;
        }
        if (!("ProductID" in $$source)) {
            this["ProductID"] = 0;
        }
        if (!("Product" in $$source)) {
            this["Product"] = "";
        }
        if (!("Serial" in $$source)) {
            this["Serial"] = "";
        }
        if (!("Manufacturer" in $$source)) {
            this["Manufacturer"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceInfo($$parsedSource as Partial<DeviceInfo>);
    }
}

export class GetKeymapReply {
    "id": string;
    "items": string[];

    /** Creates a new GetKeymapReply instance. */
    constructor($$source: Partial<GetKeymapReply> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetKeymapReply instance from a string or object.
     */
    static createFrom($$source: any = {}): GetKeymapReply {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new GetKeymapReply($$parsedSource as Partial<GetKeymapReply>);
    }
}

export class GetSettingsReply {
    "id": string;
    "swap_fn_ctrl": boolean;
    "swap_alt_cmd": boolean;
    "bluetooth_disabled": boolean;
    "io_timing": number;

    /** Creates a new GetSettingsReply instance. */
    constructor($$source: Partial<GetSettingsReply> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("swap_fn_ctrl" in $$source)) {
            this["swap_fn_ctrl"] = false;
        }
        if (!("swap_alt_cmd" in $$source)) {
            this["swap_alt_cmd"] = false;
        }
        if (!("bluetooth_disabled" in $$source)) {
            this["bluetooth_disabled"] = false;
        }
        if (!("io_timing" in $$source)) {
            this["io_timing"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSettingsReply instance from a string or object.
     */
    static createFrom($$source: any = {}): GetSettingsReply {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetSettingsReply($$parsedSource as Partial<GetSettingsReply>);
    }
}

export class SetKeymapReply {
    "id": string;
    "success": boolean;
    "error": string;

    /** Creates a new SetKeymapReply instance. */
    constructor($$source: Partial<SetKeymapReply> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetKeymapReply instance from a string or object.
     */
    static createFrom($$source: any = {}): SetKeymapReply {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetKeymapReply($$parsedSource as Partial<SetKeymapReply>);
    }
}

export class SetSettingsRequest {
    "method_name": string;
    "id": string;
    "swap_fn_ctrl": boolean;
    "swap_alt_cmd": boolean;
    "bluetooth_disabled": boolean;
    "io_timing": number;

    /** Creates a new SetSettingsRequest instance. */
    constructor($$source: Partial<SetSettingsRequest> = {}) {
        if (!("method_name" in $$source)) {
            this["method_name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("swap_fn_ctrl" in $$source)) {
            this["swap_fn_ctrl"] = false;
        }
        if (!("swap_alt_cmd" in $$source)) {
            this["swap_alt_cmd"] = false;
        }
        if (!("bluetooth_disabled" in $$source)) {
            this["bluetooth_disabled"] = false;
        }
        if (!("io_timing" in $$source)) {
            this["io_timing"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetSettingsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SetSettingsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetSettingsRequest($$parsedSource as Partial<SetSettingsRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
